on:
  push:
    branches: [ "master"]
    tags:
      - "v*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create zip file
        run: |
          cd plugins
          zip -r -j flowy-paywall.zip flowy-paywall/*
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          body: 'This is a new release of the Flowy Paywall plugin.'
          artifact: ./flowy-paywall.zip
        
